[package]
name = "titan_ecs"
version = "0.1.0"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
description = "Simple ECS for simple game engine based on Rust and Vulkan API"
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
slotmap = "1.0"
