[package]
name = "proc-macro"
version = "0.1.0"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
description = "Procedural macros for game engine API"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.73"
quote = "1.0.9"
