[package]
name = "titan-rs"
version = "0.1.0"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
description = "Simple game engine based on Rust and Vulkan API"
edition = "2018"

[workspace]

[dependencies]
titan-engine = { path = "titan-engine" }
log = "0.4.14"
chrono = "0.4.19"
log4rs = "1.0.0"
