[package]
name = "titan_core"
version = "0.1.0"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
semver = "1.0.4"
lazy_static = "1.4.0"
log = "0.4.14"
winit = "0.25.0"
vulkano = "0.25.0"
vulkano-win = "0.25.0"
vulkano-shaders = "0.25.0"
ultraviolet = "0.8.1"
palette = "0.6.0"
